remote_theme: just-the-docs/just-the-docs@v0.11.1
plugins:
- jekyll-remote-theme

nav_external_links:
  - title: Issues ðŸš€
    url: https://github.com/doug-devx/sample-public-docs-site/issues
    hide_icon: false
    opens_in_new_tab: true
